# Generated by Django 4.1.2 on 2022-10-07 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appsoftdesk", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projects",
            name="type",
            field=models.CharField(
                choices=[(1, "Back-end"), (2, "Front-end"), (3, "iOS or Android")],
                max_length=250,
            ),
        ),
    ]
