# Generated by Django 4.1.2 on 2022-10-07 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("appsoftdesk", "0003_alter_projects_author_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projects",
            name="author_user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="projects",
            name="type",
            field=models.CharField(
                choices=[
                    ("BE", "Back-end"),
                    ("FE", "Front-end"),
                    ("Mobile", "iOS or Android"),
                ],
                max_length=250,
            ),
        ),
    ]
