# Generated by Django 4.1.2 on 2022-10-07 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appsoftdesk", "0004_alter_projects_author_user_id_alter_projects_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contributors",
            name="permission",
            field=models.CharField(
                choices=[("1", "Auteur"), ("2", "Responsable"), ("3", "Créateur")],
                max_length=10,
            ),
        ),
    ]
