# Generated by Django 4.1.2 on 2022-10-12 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("appsoftdesk", "0005_alter_contributors_permission"),
    ]

    operations = [
        migrations.RenameField(
            model_name="projects", old_name="author_user_id", new_name="author_user",
        ),
    ]
