# Generated by Django 4.1.2 on 2022-10-13 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appsoftdesk", "0006_rename_author_user_id_projects_author_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comments", old_name="author_user_id", new_name="author_user",
        ),
        migrations.RenameField(
            model_name="comments", old_name="issue_id", new_name="issue",
        ),
        migrations.RenameField(
            model_name="contributors", old_name="project_id", new_name="project",
        ),
        migrations.RenameField(
            model_name="contributors", old_name="user_id", new_name="user",
        ),
        migrations.RenameField(
            model_name="issues", old_name="assignee_user_id", new_name="assignee_user",
        ),
        migrations.RenameField(
            model_name="issues", old_name="author_user_id", new_name="author_user",
        ),
        migrations.AlterField(
            model_name="projects",
            name="title",
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
