# Generated by Django 4.1.2 on 2022-10-13 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appsoftdesk", "0008_alter_projects_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projects",
            name="title",
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
