# Generated by Django 4.1.2 on 2022-10-14 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "appsoftdesk",
            "0010_alter_comments_issue_alter_contributors_project_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="contributors",
            name="permission",
            field=models.CharField(
                choices=[("Creator", "Creator"), ("Contributor", "Contributor")],
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="issues",
            name="priority",
            field=models.CharField(
                choices=[("low", "low"), ("normal", "normal"), ("high", "high")],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="issues",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="issues",
                to="appsoftdesk.projects",
            ),
        ),
        migrations.AlterField(
            model_name="issues",
            name="status",
            field=models.CharField(
                choices=[
                    ("to do", "to do"),
                    ("in progress", "in progress"),
                    ("done", "done"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="issues",
            name="tag",
            field=models.CharField(
                choices=[
                    ("bug", "bug"),
                    ("improvement", "improvement"),
                    ("task", "task"),
                ],
                max_length=250,
            ),
        ),
        migrations.AlterField(
            model_name="projects",
            name="type",
            field=models.CharField(
                choices=[
                    ("Back-end", "Back-end"),
                    ("Front-end", "Front-end"),
                    ("Mobile", "iOS or Android"),
                ],
                max_length=250,
            ),
        ),
    ]
