# Generated by Django 4.1.2 on 2022-10-24 20:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "appsoftdesk",
            "0011_alter_contributors_permission_alter_issues_priority_and_more",
        ),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="contributors", unique_together={("user", "project")},
        ),
    ]
